run:
  tests: false

issues:
  include:
    - EXC0001
    - EXC0005
    - EXC0011
    - EXC0012
    - EXC0013

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - bodyclose
    - dupl
    - exhaustive
    - exportloopref
    - goconst
    - godot
    - godox
    - goimports
    - gomnd
    - gomoddirectives
    - goprintffuncname
    - gosec
    - ifshort
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - wrapcheck
