CC=gcc
CFLAGS=-g -lm -g -std=c99 -pedantic
SRC_FILES=main.c ../helpers.c
NAME=passport

all : $(NAME)

$(NAME) : $(SRC_FILE)
	$(CC) -o $(NAME) $(SRC_FILES) $(CFLAGS)

clean : 
	rm $(NAME) 
	rm -rf $(NAME).dSYM